name: Jest Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: actions/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test -- --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3